# The ProjectRel expression is stored as a separate protobuf chunk.
# Resolving the ordinal is equivalent to placing its value inline.

root {
  input {
    project {
      input {
        read {
          named_table {
            names: "example"
          }
        }
      }
      expressions {
        detached_expression_ordinal: 0
      }
    }
  }
}
detached_expressions {
  literal {
    i64: 42
  }
}