# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: substrait/plan.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from substrait_validator.substrait import algebra_pb2 as substrait_dot_algebra__pb2
from substrait_validator.substrait.extensions import extensions_pb2 as substrait_dot_extensions_dot_extensions__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='substrait/plan.proto',
  package='substrait',
  syntax='proto3',
  serialized_options=b'\n\022io.substrait.protoP\001\252\002\022Substrait.Protobuf',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x14substrait/plan.proto\x12\tsubstrait\x1a\x17substrait/algebra.proto\x1a%substrait/extensions/extensions.proto\"X\n\x07PlanRel\x12\x1d\n\x03rel\x18\x01 \x01(\x0b\x32\x0e.substrait.RelH\x00\x12\"\n\x04root\x18\x02 \x01(\x0b\x32\x12.substrait.RelRootH\x00\x42\n\n\x08rel_type\"\x97\x02\n\x04Plan\x12@\n\x0e\x65xtension_uris\x18\x01 \x03(\x0b\x32(.substrait.extensions.SimpleExtensionURI\x12\x44\n\nextensions\x18\x02 \x03(\x0b\x32\x30.substrait.extensions.SimpleExtensionDeclaration\x12%\n\trelations\x18\x03 \x03(\x0b\x32\x12.substrait.PlanRel\x12\x44\n\x13\x61\x64vanced_extensions\x18\x04 \x01(\x0b\x32\'.substrait.extensions.AdvancedExtension\x12\x1a\n\x12\x65xpected_type_urls\x18\x05 \x03(\tB+\n\x12io.substrait.protoP\x01\xaa\x02\x12Substrait.Protobufb\x06proto3'
  ,
  dependencies=[substrait_dot_algebra__pb2.DESCRIPTOR,substrait_dot_extensions_dot_extensions__pb2.DESCRIPTOR,])




_PLANREL = _descriptor.Descriptor(
  name='PlanRel',
  full_name='substrait.PlanRel',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='rel', full_name='substrait.PlanRel.rel', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='root', full_name='substrait.PlanRel.root', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='rel_type', full_name='substrait.PlanRel.rel_type',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=99,
  serialized_end=187,
)


_PLAN = _descriptor.Descriptor(
  name='Plan',
  full_name='substrait.Plan',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='extension_uris', full_name='substrait.Plan.extension_uris', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='extensions', full_name='substrait.Plan.extensions', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='relations', full_name='substrait.Plan.relations', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='advanced_extensions', full_name='substrait.Plan.advanced_extensions', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='expected_type_urls', full_name='substrait.Plan.expected_type_urls', index=4,
      number=5, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=190,
  serialized_end=469,
)

_PLANREL.fields_by_name['rel'].message_type = substrait_dot_algebra__pb2._REL
_PLANREL.fields_by_name['root'].message_type = substrait_dot_algebra__pb2._RELROOT
_PLANREL.oneofs_by_name['rel_type'].fields.append(
  _PLANREL.fields_by_name['rel'])
_PLANREL.fields_by_name['rel'].containing_oneof = _PLANREL.oneofs_by_name['rel_type']
_PLANREL.oneofs_by_name['rel_type'].fields.append(
  _PLANREL.fields_by_name['root'])
_PLANREL.fields_by_name['root'].containing_oneof = _PLANREL.oneofs_by_name['rel_type']
_PLAN.fields_by_name['extension_uris'].message_type = substrait_dot_extensions_dot_extensions__pb2._SIMPLEEXTENSIONURI
_PLAN.fields_by_name['extensions'].message_type = substrait_dot_extensions_dot_extensions__pb2._SIMPLEEXTENSIONDECLARATION
_PLAN.fields_by_name['relations'].message_type = _PLANREL
_PLAN.fields_by_name['advanced_extensions'].message_type = substrait_dot_extensions_dot_extensions__pb2._ADVANCEDEXTENSION
DESCRIPTOR.message_types_by_name['PlanRel'] = _PLANREL
DESCRIPTOR.message_types_by_name['Plan'] = _PLAN
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PlanRel = _reflection.GeneratedProtocolMessageType('PlanRel', (_message.Message,), {
  'DESCRIPTOR' : _PLANREL,
  '__module__' : 'substrait.plan_pb2'
  # @@protoc_insertion_point(class_scope:substrait.PlanRel)
  })
_sym_db.RegisterMessage(PlanRel)

Plan = _reflection.GeneratedProtocolMessageType('Plan', (_message.Message,), {
  'DESCRIPTOR' : _PLAN,
  '__module__' : 'substrait.plan_pb2'
  # @@protoc_insertion_point(class_scope:substrait.Plan)
  })
_sym_db.RegisterMessage(Plan)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
