# Defines an identity function once and invokes it at two call sites.
#
# message Plan

version {
  major_number: 0
  minor_number: 103
  patch_number: 0
}

named_lambdas {
  lambda_anchor: 1
  name: "identity"
  lambda {
    parameters {
      types {
        i32 {
          nullability: NULLABILITY_REQUIRED
        }
      }
      nullability: NULLABILITY_REQUIRED
    }
    body {
      selection {
        lambda_parameter_reference {
          steps_out: 0
        }
        direct_reference {
          struct_field {
            field: 0
          }
        }
      }
    }
  }
}

relations {
  root {
    input {
      project {
        input {
          read {
            base_schema {
              struct {
                nullability: NULLABILITY_REQUIRED
              }
            }
            named_table {
              names: "example"
            }
          }
        }
        expressions {
          lambda_invocation {
            named_lambda_reference: 1
            arguments {
              fields {
                literal {
                  i32: 1
                }
              }
            }
          }
        }
        expressions {
          lambda_invocation {
            named_lambda_reference: 1
            arguments {
              fields {
                literal {
                  i32: 2
                }
              }
            }
          }
        }
      }
    }
    names: "first"
    names: "second"
  }
}

execution_behavior {
  variable_eval_mode: VARIABLE_EVALUATION_MODE_PER_PLAN
}