# Represents: `(outer_x: i32) -> ((inner_y: i32) -> add(outer_x, inner_y))`
# Demonstrates steps_out:
#   - steps_out: 1 with struct_field: 0 -> outer_x
#   - steps_out: 0 with struct_field: 0 -> inner_y
#
# message Expression.Lambda
parameters: {types: [{i32: {nullability: NULLABILITY_REQUIRED}}]}
body: {
  lambda: {
    parameters: {types: [{i32: {nullability: NULLABILITY_REQUIRED}}]}
    body: {
      scalar_function: {
        function_reference: 1
        arguments: [
          {value: {selection: {lambda_parameter_reference: {steps_out: 1}, direct_reference: {struct_field: {field: 0}}}}},  # outer_x
          {value: {selection: {lambda_parameter_reference: {steps_out: 0}, direct_reference: {struct_field: {field: 0}}}}}   # inner_y
        ]
      }
    }
  }
}
